// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:english_by_holamellamoyago/presentation/screens.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: Environment.firebaseWebKey,
    appId: '1:1050588380052:web:393ab3a57f19f20b83ed81',
    messagingSenderId: '1050588380052',
    projectId: 'hiitgym-2ae99',
    authDomain: 'hiitgym-2ae99.firebaseapp.com',
    databaseURL: 'https://hiitgym-2ae99-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hiitgym-2ae99.appspot.com',
    measurementId: 'G-6G937QH87S',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: Environment.firebaseAndroidKey,
    appId: '1:1050588380052:android:9210a1dff69519a983ed81',
    messagingSenderId: '1050588380052',
    projectId: 'hiitgym-2ae99',
    databaseURL: 'https://hiitgym-2ae99-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hiitgym-2ae99.appspot.com',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: Environment.firebaseIOSKey,
    appId: '1:1050588380052:ios:316c0e4b3903e40683ed81',
    messagingSenderId: '1050588380052',
    projectId: 'hiitgym-2ae99',
    databaseURL: 'https://hiitgym-2ae99-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hiitgym-2ae99.appspot.com',
    androidClientId: '1050588380052-37oag1gu9s9in7bupgon7od7n2id33cg.apps.googleusercontent.com',
    iosClientId: '1050588380052-u9c2pmmeotjdpc707eq3f84vbmuk97j0.apps.googleusercontent.com',
    iosBundleId: 'com.holamellamoyago.englishbyyago',
  );
}
