name: english_by_holamellamoyago
description: "Página web hecha por Yago Otero que permite aprender inglés de una forma dinámica y divertida"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  hovering: ^1.0.4
  seo: ^0.0.9
  sizer: ^2.0.15

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
