name: english_by_holamellamoyago
description: "Página web hecha por Yago Otero que permite aprender inglés de una
  forma dinámica y divertida"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animated_loading_border: ^0.0.2
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  hovering: ^1.0.4
  shared_preferences: ^2.3.3
  sizer: ^2.0.15
  supabase_flutter: ^2.8.2

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
