// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3S4CuSviuZagMm7-I3S8F1E6AJLCz3y8',
    appId: '1:122440637695:web:5771e93e7366d14e4600ca',
    messagingSenderId: '122440637695',
    projectId: 'pharsal-quest',
    authDomain: 'pharsal-quest.firebaseapp.com',
    storageBucket: 'pharsal-quest.firebasestorage.app',
    measurementId: 'G-C51NHM53SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4YDr14nOwuyg0TjRXPN8zbPqwgmu4wtY',
    appId: '1:122440637695:android:ef3892d695bf86fb4600ca',
    messagingSenderId: '122440637695',
    projectId: 'pharsal-quest',
    storageBucket: 'pharsal-quest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuOtqDgp5Zdvy88EHL-XefM2Sj8XzU1FA',
    appId: '1:122440637695:ios:cc777c4c2466e92c4600ca',
    messagingSenderId: '122440637695',
    projectId: 'pharsal-quest',
    storageBucket: 'pharsal-quest.firebasestorage.app',
    iosBundleId: 'com.new.yagooterom.phrasalquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuOtqDgp5Zdvy88EHL-XefM2Sj8XzU1FA',
    appId: '1:122440637695:ios:5c7115bca0b494274600ca',
    messagingSenderId: '122440637695',
    projectId: 'pharsal-quest',
    storageBucket: 'pharsal-quest.firebasestorage.app',
    iosBundleId: 'com.example.englishMvvmProviderClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3S4CuSviuZagMm7-I3S8F1E6AJLCz3y8',
    appId: '1:122440637695:web:dee48dd831f63aac4600ca',
    messagingSenderId: '122440637695',
    projectId: 'pharsal-quest',
    authDomain: 'pharsal-quest.firebaseapp.com',
    storageBucket: 'pharsal-quest.firebasestorage.app',
    measurementId: 'G-VZYKHPWZC7',
  );
}
